### PR TITLE
fix bugs in CRLF injection protection

### LINKED ISSUE #1: CRLF injection
https://gratipay.freshdesk.com/helpdesk/tickets/2305

> == CRLF Injection (Chrome, Internet Explorer) ==
> http://gratipay.com/%0dSet-Cookie:csrf_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
> 
> Response:
> Location: https://gratipay.com/\r
> Set-Cookie:csrf_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;\r\n

### PR DESCRIPTION
**Pull request by chadwhitacre**
Fixes #1.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Ready for review, @pjz.

**Comment by chadwhitacre** [comment]
@pjz Let's merge this and then cut a release, eh?

**Comment by chadwhitacre** [comment]
Gah, I effed us up with a force-push to `upstream`, sorry @pjz. :-/

/me looking at repair ...

**Comment by chadwhitacre** [comment]
(I was confused as to why AppVeyor was on this PR.)

**Comment by pjz** [comment]
You should be able to set the output of this merge as `master`, no?

**Comment by chadwhitacre** [comment]
@pjz I just went ahead and merged locally and pushed in:

https://github.com/gratipay/aspen-python/commit/a87e62225e6d2f172ca0a1383485866707285f42
https://github.com/gratipay/aspen-python/commit/a32cbe53ebc64b40a1ddbf5e363d32897afc0ef9
https://github.com/gratipay/aspen-python/commit/02109feb89668beb4b6985037fcae0317ac6c4bd

**Pull request merged**
